name: Build android package

on:
  push:
    branches: [ con-wrappers ]
  pull_request:
    branches: [ con-wrappers ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        sudo apt-get update
        sudo apt install -y make openjdk-8-jdk openjdk-8-jre ant-contrib python3-requests python3-pip
        sudo pip3 install websocket-client
        git clone --depth 1 https://gitlab.com/LostGamer/ndk-binaries
        git clone --depth 1 https://gitlab.com/LostGamer/android-sdk
        git clone --depth 1 https://github.com/nillerusr/srcsdk
        cd srcsdk
        git submodule init && git submodule update
        cd ../

        scripts/workflow.sh

        JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/ ANDROID_HOME=android-sdk/ ant debug

    - name: Upload files
      shell: bash
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      run: |
        echo -e "Commits history: https://github.com/nillerusr/srceng-android/commits/con-wrappers\nBuild: $(curl -s --upload-file bin/srceng-debug.apk https://oshi.at/source_engine-$(date +%Y-%m-%d-%H-%M).apk/43200 | grep Direct)\nBuild finished at: $(date +%Y-%m-%d-%H:%M)" > text
        python3 scripts/upload-to-discord.py
